### PR TITLE
Add some exe names for Chrome in Linux

### PR DESCRIPTION
**Pull request by anjianshi**
copy from karma-chrome-launcher

### CODE REVIEW

**Comment by 4kochi** [comment]
Thx for your pull request. We will have a look at the Travis errors and then merge it.

**Comment by 4kochi** [comment]
The Travis CI builds fail now. Can you please check if this is only a problem with travis.

**Comment by anjianshi** [comment]
Seems it's a problem of Karma (or Travis-CI ?). 
And here is a temporary solution:
https://github.com/karma-runner/karma/issues/1144#issuecomment-53633076
Now, it can pass tests, but the code maybe not so beautiful. ^_^

**Comment by 4kochi** [comment]
Thanks for contributing. Published as version 2.0.1

**Comment by anjianshi** [comment]
^_^

**Pull request merged**
